platform :ios, ‘9.0’
target “wechat” do
pod 'AFNetworking', '~> 3.0'
pod 'Masonry', '~> 1.0.2'
pod 'MJExtension', '~> 3.0.13'
pod 'MJRefresh', '~> 3.1.12'
pod 'Hyphenate'
pod 'TTTAttributedLabel'
pod 'TZImagePickerController'
pod 'MBProgressHUD'
pod 'SDWebImage'
pod 'FMDB', '~> 2.7.2'
end
